version: "3.6"

services:
  web:
    image: template-docker-django
    build:
      context: .
    ports:
      - 8000:80
    environment:
      - ENVIRONMENT
      - SENTRY_DSN
      - DB_HOST
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DJANGO_SECRET_KEY
    volumes:
      - .:/app
    command: python /app/src/manage.py runserver 0.0.0.0:80
